// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Oe5FStXD7_bfdFcR1U4G-acTrn07tnA',
    appId: '1:989878609925:web:5521bb6f9916f46497146c',
    messagingSenderId: '989878609925',
    projectId: 'arms-bf4ae',
    authDomain: 'arms-bf4ae.firebaseapp.com',
    storageBucket: 'arms-bf4ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGVHGtshRhfGi1Jx8DEA38N0TAJurHKCE',
    appId: '1:989878609925:android:ecb05cb29e29a3bd97146c',
    messagingSenderId: '989878609925',
    projectId: 'arms-bf4ae',
    storageBucket: 'arms-bf4ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFJvl-9FaHiiYC9gbS6iDfDnvTX4duVg',
    appId: '1:989878609925:ios:08991d0543ecbdba97146c',
    messagingSenderId: '989878609925',
    projectId: 'arms-bf4ae',
    storageBucket: 'arms-bf4ae.appspot.com',
    iosBundleId: 'com.example.arms',
  );
}
